### ISSUE TITLE
Microsoft Bot Emulator-BOT replies are coming twice and thrice

### ISSUE THREAD

**Issue by Ritika3108** [codeforequity-at/botium-cli#14]
After connecting to Bot the welcome message is getting displayed thrice and other conversational  messages are getting displayed twice
[Botium_doublemessagereply.docx](https://github.com/codeforequity-at/botium-cli/files/2266106/Botium_doublemessagereply.docx)

![image](https://user-images.githubusercontent.com/42173967/43771765-cdd3863c-9a5d-11e8-9892-e2e55e4f1070.png)

**Comment by codeforequity-at** [comment]
Please use the latest build. This problem was already fixed in the botium connector source, but the fix hasn't been included in Botium-CLI up to now.
