### ISSUE TITLE
Adaptive cards are not getting displayed

### ISSUE THREAD

**Issue by Ritika3108** [codeforequity-at/botium-cli#15]
We are using Microsoft BOt framework, However, we are unable to see the adaptive cards that we are receiving from the BOT end.

In the attached image, the dynamic adaptive card is supposed to be displayed with HCP details, However, it doesn't display anything

![image](https://user-images.githubusercontent.com/42173967/43817950-e5314908-9af9-11e8-9b38-0a7d7f07859d.png)

**Comment by codeforequity-at** [comment]
The simple emulator interface doesn't show up anything but plain text currently. Adaptive cards (or any other multimedia content) is supported by Botium itself, but not by this companion tool.
