### ISSUE TITLE
Multiple Botium Dialogflow Input Context Name and LifeSpans in botium.json

### ISSUE THREAD

**Issue by Arun-wws** [codeforequity-at/botium-cli#16]
Currently, I'm unable to define multiple input context names and life-spans in botium.json.

I may want to declare multiple Botium Input Context names and Life-Span as below in botium.json.
Let me know if it's possible to do this.

"DIALOGFLOW_INPUT_CONTEXT_NAME": ["botiumtest1","botiumtest2","botiumtest3"],
and "DIALOGFLOW_INPUT_CONTEXT_LIFESPAN":[3,2,2]

**Comment by codeforequity-at** [comment]
The latest build provides this feature. Please look at the "[samples](https://github.com/codeforequity-at/botium-connector-dialogflow/tree/master/samples)" directory for an example.
