### ISSUE TITLE
How to use date expressions in botium?

### ISSUE THREAD

**Issue by ram-d** [codeforequity-at/botium-cli#46]
Hi @codeforequity-at ,

We are using $today for the current date in botium. Is there a way we can retrieve yesterday's date or tomorrow's date? Is it possible to use $today+1 or -1 ?

Thank you,
Ram

**Comment by codeforequity-at** [comment]
You will have to use the *$func(some javascript code)* placeholder to run some javascript code for this

**Comment by codeforequity-at** [comment]
We added some additional scripting functions in the latest build

https://botium-docs.readthedocs.io/en/latest/05_botiumscript/index.html#list-of-functions

    $yesterday
    $tomorrow
    $date_add(1, “day”, YYYY.MM.DD)
